#
# Workflows triggered by PRs submitted from forked repositories
# (all of ours) are severly limited in what they can do.
# For instance, they can't add or remove labels or comments even
# on the PR that triggered them.  Since we need to both of those,
# GitHub recommends creating a separate workflow (this one) that
# does those tasks that's triggered when the PR submit workflow
# starts or finishes.  Since this workflow isn't being run in the
# context of a forked repo, it has all the privileges needed to
# add and remove labels and comments. Hence the "Priv" at the end
# of this workflow name.
#
name: PRChangedPriv
run-name: "PRChangedPriv ${{ github.event.workflow_run.name }} ${{ github.event.action }}(${{ github.event.workflow_run.conclusion }})"
on:
  workflow_run:
    workflows: [PRChanged]
    types:
      - requested
      - completed

jobs:
  PRChangedPriv:
    name: "run-checkpriv"
    uses: asterisk/asterisk-ci-actions/.github/workflows/AsteriskPRChangedPriv.yml@main
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
